import os from "node:os";
import path from "node:path";
import dns from "node:dns";
import { createReadStream, existsSync } from "node:fs";
import { execFile, spawn } from "node:child_process";
import { mkdir, readdir, rm, writeFile, readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { promisify } from "node:util";
import { jobManager } from "@/lib/JobQueue";

if (dns && dns.setDefaultResultOrder) {
  dns.setDefaultResultOrder("ipv4first");
}
import {
  formatBytes,
  formatDurationSeconds,
  formatSourceName,
  sanitizeFilename
} from "@/utils/helpers";

const execFileAsync = promisify(execFile);
const YT_DLP_BIN = process.env.YT_DLP_BIN || "yt-dlp";
const TMP_ROOT = path.join(os.tmpdir(), "fetch-by-the-atom");
const ALLOW_YOUTUBE_ADAPTIVE = process.env.ALLOW_YOUTUBE_ADAPTIVE !== "false";

// Track consecutive YouTube failures globally to trigger process exit / IP rotation if blocked.
if (global.__consecutiveYoutubeFailures === undefined) {
  global.__consecutiveYoutubeFailures = 0;
}

function incrementYoutubeFailures() {
  global.__consecutiveYoutubeFailures++;
  console.warn(`ytDlp: YouTube inspection failed. Consecutive failure count: ${global.__consecutiveYoutubeFailures}/3`);
  
  if (global.__consecutiveYoutubeFailures >= 3) {
    if (jobManager.running.size === 0) {
      if (process.uptime() < 300) {
        console.warn("ytDlp: 3 consecutive YouTube failures detected, but server uptime is less than 5 minutes. Skipping proactive restart to avoid container crash loops.");
        return;
      }
      console.warn("ytDlp: 3 consecutive YouTube failures detected and server is idle. Restarting process to rotate container IP...");
      setTimeout(() => {
        process.exit(1);
      }, 1000);
    } else {
      console.warn(`ytDlp: 3 consecutive YouTube failures detected, but active downloads are running. Deferring restart until queue is empty.`);
      global.__needsSelfRestart = true;
    }
  }
}

function resetYoutubeFailures() {
  if (global.__consecutiveYoutubeFailures > 0) {
    console.log(`ytDlp: YouTube inspection succeeded. Resetting consecutive failures from ${global.__consecutiveYoutubeFailures} to 0.`);
    global.__consecutiveYoutubeFailures = 0;
  }
}

// Persist across Next.js HMR hot-module reloads in dev.
// In production this is just a regular Map on the module.
if (!global.__activeDownloads) {
  global.__activeDownloads = new Map();
}
export const activeDownloads = global.__activeDownloads;

function convertJsonToNetscape(jsonContent) {
  let cookies;
  try {
    cookies = JSON.parse(jsonContent);
  } catch (e) {
    throw new Error("Failed to parse JSON cookie content: " + e.message);
  }

  // Check if it's the encrypted/internal backup format of Hotcleaner Cookie-Editor
  if (cookies && !Array.isArray(cookies) && typeof cookies === "object" && cookies.data) {
    throw new Error(
      "The provided cookies.json file is an encrypted Cookie-Editor backup. Please export your cookies as 'JSON' or 'Netscape' from the extension instead of creating a 'Backup' file."
    );
  }

  if (!Array.isArray(cookies)) {
    throw new Error("JSON cookies must be a JSON array of cookie objects.");
  }

  let output = "# Netscape HTTP Cookie File\n# This file was generated by fetch-by-the-atom converter\n\n";

  for (const cookie of cookies) {
    if (!cookie.name || !cookie.domain) {
      continue;
    }
    const domain = cookie.domain;
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const path = cookie.path || "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    
    let expiration = 0;
    if (typeof cookie.expirationDate === "number") {
      expiration = Math.round(cookie.expirationDate);
    } else if (typeof cookie.expiry === "number") {
      expiration = Math.round(cookie.expiry);
    }
    
    const name = cookie.name;
    const value = cookie.value || "";

    output += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
  }

  return output;
}

let lastProcessedBase64 = null;

async function getCookiesArg(sourceUrl, forceCookies = false) {
  const isYouTube = sourceUrl && (sourceUrl.includes("youtube.com") || sourceUrl.includes("youtu.be"));
  if (isYouTube && !forceCookies) {
    console.log("getCookiesArg: Bypassing cookies for YouTube URL by default");
    return [];
  }

  const tmpTxtPath = path.join(os.tmpdir(), "fetch-by-the-atom-cookies.txt");
  
  console.log("getCookiesArg: Checking cookies configuration...");
  // 1. Decode/convert from environment variable if available
  if (process.env.YT_DLP_COOKIES_BASE64) {
    const rawLen = process.env.YT_DLP_COOKIES_BASE64.length;
    console.log(`getCookiesArg: YT_DLP_COOKIES_BASE64 env var found. Length: ${rawLen}`);
    if (process.env.YT_DLP_COOKIES_BASE64 !== lastProcessedBase64 || !existsSync(tmpTxtPath)) {
      try {
        // Clean all whitespace from the environment variable
        const cleanBase64 = process.env.YT_DLP_COOKIES_BASE64.replace(/\s/g, "");
        console.log(`getCookiesArg: Cleaned base64 length: ${cleanBase64.length}`);
        // Split by base64 delimiters (comma, semicolon) or padding (=, ==) to handle concatenated values
        const chunks = cleanBase64.split(/[,;=]+/).filter(Boolean);
        
        let mergedCookiesContent = "# Netscape HTTP Cookie File\n# This file was generated by fetch-by-the-atom converter\n\n";
        let processedCount = 0;
        
        for (const chunk of chunks) {
          const decoded = Buffer.from(chunk, "base64").toString("utf-8").trim();
          if (!decoded) continue;
          
          const isJson = decoded.startsWith("[") || decoded.startsWith("{");
          if (isJson) {
            try {
              const converted = convertJsonToNetscape(decoded);
              // Strip header comment lines if any, to merge cleanly
              const cleanConverted = converted.replace(/^(#.*?\n)*/s, "");
              mergedCookiesContent += `\n# Cookies Chunk ${processedCount + 1} (JSON converted)\n` + cleanConverted;
              processedCount++;
            } catch (jsonErr) {
              console.warn(`getCookiesArg: Chunk ${processedCount + 1} looked like JSON but failed to convert:`, jsonErr.message);
              // Fall back to treating it as Netscape/plain text
              const cleanContent = decoded.replace(/^(#.*?\n)*/s, "");
              mergedCookiesContent += `\n# Cookies Chunk ${processedCount + 1} (Plain Text Fallback)\n` + cleanContent;
              processedCount++;
            }
          } else {
            const cleanContent = decoded.replace(/^(#.*?\n)*/s, "");
            mergedCookiesContent += `\n# Cookies Chunk ${processedCount + 1} (Netscape Format)\n` + cleanContent;
            processedCount++;
          }
        }
        
        if (processedCount === 0) {
          throw new Error("No valid cookie content could be decoded from YT_DLP_COOKIES_BASE64.");
        }
        
        const sanitizedContent = mergedCookiesContent.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "");
        await writeFile(tmpTxtPath, sanitizedContent, "utf-8");
        lastProcessedBase64 = process.env.YT_DLP_COOKIES_BASE64;
        console.log(`getCookiesArg: Successfully processed and merged ${processedCount} cookie chunks from environment variable.`);
      } catch (e) {
        console.error("getCookiesArg: Failed to process YT_DLP_COOKIES_BASE64:", e);
        throw new Error(`Failed to process environment cookies: ${e.message}`);
      }
    }
    
    if (existsSync(tmpTxtPath)) {
      console.log("getCookiesArg: Using environment cookies file.");
      return ["--cookies", tmpTxtPath];
    }
  } else {
    console.log("getCookiesArg: YT_DLP_COOKIES_BASE64 env var NOT found.");
  }
  
  // 2. Check for local cookie files (JSON preferred, then Netscape txt)
  let localFiles = [];
  try {
    const files = await readdir(process.cwd());
    for (const file of files) {
      const lower = file.toLowerCase();
      if (lower.endsWith("cookies.json") || lower.endsWith("cookie.json")) {
        localFiles.push({ path: path.join(process.cwd(), file), isJson: true, name: file, priority: 1 });
      } else if (lower.endsWith("cookies.txt") || lower.endsWith("cookie.txt")) {
        localFiles.push({ path: path.join(process.cwd(), file), isJson: false, name: file, priority: 2 });
      }
    }
    // Sort so JSON files are processed before TXT files
    localFiles.sort((a, b) => a.priority - b.priority);
  } catch (e) {
    console.error("Failed to read local directory for cookies:", e);
  }
  
  let lastError = null;
  let mergedCookiesContent = "# Netscape HTTP Cookie File\n# This file was generated by fetch-by-the-atom converter\n\n";
  let loadedCount = 0;

  for (const item of localFiles) {
    if (existsSync(item.path)) {
      try {
        const content = await readFile(item.path, "utf-8");
        const trimmed = content.trim();
        if (!trimmed) continue;
        const isJson = trimmed.startsWith("[") || trimmed.startsWith("{");
        
        if (isJson) {
          const converted = convertJsonToNetscape(trimmed);
          const cleanConverted = converted.replace(/^(#.*?\n)*/s, "");
          mergedCookiesContent += `\n# Cookies from ${item.name}\n` + cleanConverted;
          loadedCount++;
          console.log(`Successfully converted and merged cookies from local file: ${item.name}`);
        } else {
          const cleanContent = trimmed.replace(/^(#.*?\n)*/s, "");
          mergedCookiesContent += `\n# Cookies from ${item.name}\n` + cleanContent;
          loadedCount++;
          console.log(`Successfully merged cookies from local Netscape file: ${item.name}`);
        }
      } catch (e) {
        console.error(`Failed to process local cookie file at ${item.path}:`, e.message);
        lastError = e;
      }
    }
  }

  if (loadedCount > 0) {
    const sanitizedContent = mergedCookiesContent.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "");
    await writeFile(tmpTxtPath, sanitizedContent, "utf-8");
    console.log(`Successfully merged and loaded ${loadedCount} cookie files.`);
    return ["--cookies", tmpTxtPath];
  }

  if (lastError) {
    throw lastError;
  }
  
  // 3. Fallback to existing tmpTxtPath if neither env nor local files are found/valid
  if (existsSync(tmpTxtPath)) {
    return ["--cookies", tmpTxtPath];
  }
  
  return [];
}

async function hasCookiesConfigured() {
  if (process.env.YT_DLP_COOKIES_BASE64) {
    return true;
  }
  try {
    const files = await readdir(process.cwd());
    for (const file of files) {
      const lower = file.toLowerCase();
      if (
        lower.endsWith("cookies.json") ||
        lower.endsWith("cookie.json") ||
        lower.endsWith("cookies.txt") ||
        lower.endsWith("cookie.txt")
      ) {
        return true;
      }
    }
  } catch (e) {
    // Ignore error
  }
  return false;
}

function createYtError(message, statusCode = 500) {
  const error = new Error(message);
  error.statusCode = statusCode;
  return error;
}

function createTempId() {
  return randomUUID();
}

function guessMimeType(ext = "") {
  const normalized = ext.toLowerCase();

  if (normalized === "mp4" || normalized === "m4v") {
    return "video/mp4";
  }

  if (normalized === "webm") {
    return "video/webm";
  }

  if (normalized === "mp3") {
    return "audio/mpeg";
  }

  if (normalized === "m4a") {
    return "audio/mp4";
  }

  if (normalized === "jpg" || normalized === "jpeg") {
    return "image/jpeg";
  }

  if (normalized === "png") {
    return "image/png";
  }

  return "application/octet-stream";
}

function normalizeExt(ext = "", fallback = "mp4") {
  return String(ext || fallback).toLowerCase();
}

function isYouTubeLikeSource(value = "") {
  const normalized = String(value || "").toLowerCase();
  return normalized.includes("youtube") || normalized.includes("youtu.be");
}

function getCodecPriority(format) {
  const codec = String(format.vcodec || "").toLowerCase();

  if (codec.includes("avc") || codec.includes("h264")) {
    return 3;
  }

  if (codec.includes("vp9")) {
    return 2;
  }

  if (codec.includes("av01")) {
    return 1;
  }

  return 0;
}

function isPrimaryAudioTrack(format) {
  const note = String(format.format_note || "").toLowerCase();

  if (note.includes("drc")) {
    return false;
  }

  if (note.includes("original (default)")) {
    return true;
  }

  return !/-\d+$/.test(String(format.format_id || ""));
}

function pickBetterVideoFormat(current, next) {
  if (!current) {
    return next;
  }

  const currentProgressive = current.acodec !== "none";
  const nextProgressive = next.acodec !== "none";

  if (currentProgressive !== nextProgressive) {
    return nextProgressive ? next : current;
  }

  const currentCodec = getCodecPriority(current);
  const nextCodec = getCodecPriority(next);

  if (currentCodec !== nextCodec) {
    return nextCodec > currentCodec ? next : current;
  }

  return (next.tbr || 0) > (current.tbr || 0) ? next : current;
}

function sortByContainerThenQuality(groups = []) {
  return [...groups]
    .sort((first, second) => first.container.localeCompare(second.container))
    .map((group) => ({
      ...group,
      items: [...group.items].sort((first, second) => {
        if (first.type === "video") {
          return (second.qualityValue || 0) - (first.qualityValue || 0);
        }

        return (second.qualityValue || 0) - (first.qualityValue || 0);
      })
    }));
}

function estimateSizeBytes(format, durationSeconds = 0) {
  // Prefer exact filesize, then approximate filesize
  if (format.filesize && format.filesize > 0) return format.filesize;
  if (format.filesize_approx && format.filesize_approx > 0) return format.filesize_approx;
  // Fall back to bitrate × duration estimation (tbr is in kbps)
  const tbr = format.tbr || format.vbr || 0;
  if (tbr > 0 && durationSeconds > 0) {
    return Math.round((tbr * 1000 / 8) * durationSeconds);
  }
  return 0;
}

function getResolutionSuffix(height) {
  if (height >= 2160) return " (4K)";
  if (height >= 1440) return " (2K)";
  if (height >= 1080) return " (Full HD)";
  if (height >= 720) return " (HD)";
  return "";
}

function buildVideoGroups(formats = [], durationSeconds = 0) {
  const bestPerVariant = new Map();

  for (const format of formats) {
    if (!format?.format_id || format.vcodec === "none" || !format.ext || format.ext === "mhtml") {
      continue;
    }

    const key = `${format.ext}:${format.height || 0}:${format.fps || 0}`;
    const current = bestPerVariant.get(key);
    bestPerVariant.set(key, pickBetterVideoFormat(current, format));
  }

  // Find the single best progressive format per container to mark as "(Recommended)"
  const bestProgressivePerContainer = new Map();
  for (const format of bestPerVariant.values()) {
    const progressive = format.acodec !== "none";
    if (progressive) {
      const container = format.ext.toUpperCase();
      const currentBest = bestProgressivePerContainer.get(container);
      if (!currentBest) {
        bestProgressivePerContainer.set(container, format);
      } else {
        const currentBestHeight = currentBest.height || 0;
        const formatHeight = format.height || 0;
        if (formatHeight > currentBestHeight) {
          bestProgressivePerContainer.set(container, format);
        } else if (formatHeight === currentBestHeight) {
          const currentBestTbr = currentBest.tbr || 0;
          const formatTbr = format.tbr || 0;
          if (formatTbr > currentBestTbr) {
            bestProgressivePerContainer.set(container, format);
          }
        }
      }
    }
  }

  const grouped = new Map();

  for (const format of bestPerVariant.values()) {
    const progressive = format.acodec !== "none";
    const container = format.ext.toUpperCase();
    const resolution = format.height ? `${format.height}p` : format.format_note || "Video";
    const fps = format.fps ? `${format.fps}fps` : null;
    const mode = progressive ? "direct" : "merge";

    // We disable CPU-heavy video transcoding (e.g. VP9/AV1 to H.264) on the server.
    // Transcoding high resolution (1080p, 1440p, 4K) videos on a cloud container
    // causes high CPU usage, timeouts, and failures. Stream copy is instant and lossless.
    const needsRecode = false;

    const note = progressive
      ? [resolution, fps, "Ready with audio"].filter(Boolean).join(" • ")
      : [resolution, fps, "Server merge required"].filter(Boolean).join(" • ");
    const sizeBytes = estimateSizeBytes(format, durationSeconds);
    const labelBase = format.height ? `${format.height}p${getResolutionSuffix(format.height)}` : format.format_note || "Video";
    
    const isRecommended = progressive && bestProgressivePerContainer.get(container) === format;

    const option = {
      id: `video:${format.format_id}:${mode}`,
      selector: progressive ? format.format_id : `${format.format_id}+bestaudio/best`,
      mode,
      type: "video",
      isAdaptive: !progressive,
      needsRecode,
      ext: normalizeExt(format.ext, "mp4"),
      container,
      label: isRecommended ? `${labelBase} (Recommended)` : labelBase,
      note,
      qualityValue: format.height || 0,
      sizeBytes,
      sizeLabel: formatBytes(sizeBytes),
      requiresServerSupport: !progressive
    };

    if (!grouped.has(container)) {
      grouped.set(container, {
        container,
        type: "video",
        items: []
      });
    }

    grouped.get(container).items.push(option);
  }

  return sortByContainerThenQuality([...grouped.values()]);
}

function buildAudioGroups(formats = [], durationSeconds = 0) {
  const primaryFormats = formats.filter((format) => (
    format?.format_id &&
    format.vcodec === "none" &&
    format.acodec !== "none" &&
    format.ext &&
    format.ext !== "mhtml" &&
    isPrimaryAudioTrack(format)
  ));

  const grouped = new Map();

  for (const format of primaryFormats) {
    const container = format.ext.toUpperCase();
    const bitrate = Math.round(format.abr || format.tbr || 0);
    const sizeBytes = estimateSizeBytes(format, durationSeconds);
    const option = {
      id: `audio:${format.format_id}:direct`,
      selector: format.format_id,
      mode: "direct",
      type: "audio",
      ext: normalizeExt(format.ext, "m4a"),
      container,
      label: bitrate ? `${bitrate}kbps` : "Audio",
      note: "Original audio track",
      qualityValue: bitrate,
      sizeBytes,
      sizeLabel: formatBytes(sizeBytes),
      requiresServerSupport: false
    };

    if (!grouped.has(container)) {
      grouped.set(container, {
        container,
        type: "audio",
        items: []
      });
    }

    grouped.get(container).items.push(option);
  }

  // Estimate MP3 size from the best available audio bitrate × duration
  const bestAudioBitrate = Math.max(
    ...primaryFormats.map((f) => f.abr || f.tbr || 0).filter(Boolean),
    0
  );
  const mp3SizeBytes = bestAudioBitrate > 0 && durationSeconds > 0
    ? Math.round((bestAudioBitrate * 1000 / 8) * durationSeconds)
    : 0;

  const mp3Group = {
    container: "MP3",
    type: "audio",
    items: [
      {
        id: "audio:bestaudio:extract-mp3",
        selector: "bestaudio/best",
        mode: "extract-audio",
        type: "audio",
        isAdaptive: false,
        ext: "mp3",
        container: "MP3",
        label: "Best available",
        note: "Converted to MP3 on the server",
        qualityValue: 999,
        sizeBytes: mp3SizeBytes,
        sizeLabel: mp3SizeBytes > 0 ? `~${formatBytes(mp3SizeBytes)}` : "Unknown",
        requiresServerSupport: true
      }
    ]
  };

  return sortByContainerThenQuality([...grouped.values(), mp3Group]);
}

function normalizeFormats(info) {
  const durationSeconds = info.duration || 0;
  const video = buildVideoGroups(info.formats || [], durationSeconds);
  const audio = buildAudioGroups(info.formats || [], durationSeconds);
  const flat = [...video.flatMap((group) => group.items), ...audio.flatMap((group) => group.items)];

  if (!flat.length) {
    const fallback = {
      id: "video:best:direct",
      selector: "best",
      mode: "direct",
      type: "video",
      isAdaptive: false,
      ext: normalizeExt(info.ext, "mp4"),
      container: String(info.ext || "file").toUpperCase(),
      label: `Best available ${String(info.ext || "file").toUpperCase()}`,
      note: "Let the server pick the best direct format",
      qualityValue: 0,
      sizeBytes: 0,
      sizeLabel: "Unknown",
      requiresServerSupport: false
    };

    return {
      video: [{ container: fallback.container, type: "video", items: [fallback] }],
      audio: [],
      flat: [fallback]
    };
  }

  return { video, audio, flat };
}

function applyServerAvailability(formats, { serverWarning = "", sourceUrl = "", sourceName = "" } = {}) {
  const blockAdaptiveYouTube = !ALLOW_YOUTUBE_ADAPTIVE && (
    isYouTubeLikeSource(sourceUrl) || isYouTubeLikeSource(sourceName)
  );
  const adaptiveReason = blockAdaptiveYouTube
    ? "Higher YouTube qualities like 1080p, 1440p, and 4K are disabled on this server because they need extra YouTube download support. Use a direct quality here, or upgrade the server setup first."
    : serverWarning;

  if (!adaptiveReason) {
    return formats;
  }

  const markItem = (item) => {
    if (item.type === "video" && item.isAdaptive) {
      return {
        ...item,
        disabled: true,
        unavailableReason: adaptiveReason,
        note: `${item.note} • currently unavailable on this server`
      };
    }

    return item;
  };

  const video = formats.video.map((group) => ({
    ...group,
    items: group.items.map(markItem)
  }));
  const audio = formats.audio.map((group) => ({
    ...group,
    items: group.items.map(markItem)
  }));
  const flat = [...video.flatMap((group) => group.items), ...audio.flatMap((group) => group.items)];

  return { video, audio, flat };
}

function normalizeWarningText(stderr = "") {
  const lower = stderr.toLowerCase();

  if (lower.includes("po token") || lower.includes("sabr streaming")) {
    return "Some higher YouTube qualities may need a newer yt-dlp build or a configured YouTube PO token on the server.";
  }

  return "";
}

function shortcodeToId(shortcode) {
  let id = BigInt(0);
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
  for (let i = 0; i < shortcode.length; i++) {
    const char = shortcode[i];
    const value = alphabet.indexOf(char);
    if (value === -1) {
      throw new Error(`Invalid character in shortcode: ${char}`);
    }
    id = id * BigInt(64) + BigInt(value);
  }
  return id.toString();
}

async function getInstagramCookieString() {
  let instagramCookies = [];
  
  // 1. Check env var
  if (process.env.YT_DLP_COOKIES_BASE64) {
    try {
      const cleanBase64 = process.env.YT_DLP_COOKIES_BASE64.replace(/\s/g, "");
      const chunks = cleanBase64.split(/[,;=]+/).filter(Boolean);
      for (const chunk of chunks) {
        const decoded = Buffer.from(chunk, "base64").toString("utf-8").trim();
        if (!decoded) continue;
        const isJson = decoded.startsWith("[") || decoded.startsWith("{");
        if (isJson) {
          try {
            const parsed = JSON.parse(decoded);
            if (Array.isArray(parsed)) {
              const filtered = parsed.filter(c => c.domain && c.domain.includes("instagram.com"));
              instagramCookies.push(...filtered);
            }
          } catch {}
        } else {
          // Netscape parser for environment cookie chunks
          const lines = decoded.split("\n");
          for (const line of lines) {
            if (line.startsWith("#") || !line.trim()) continue;
            const parts = line.split("\t");
            if (parts.length >= 7) {
              const domain = parts[0];
              const name = parts[5];
              const value = parts[6]?.trim() || "";
              if (domain.includes("instagram.com")) {
                instagramCookies.push({ name, value, domain });
              }
            }
          }
        }
      }
    } catch (e) {
      console.error("Error parsing YT_DLP_COOKIES_BASE64 for Instagram:", e);
    }
  }
  
  // 2. Read local files
  try {
    const files = await readdir(process.cwd());
    for (const file of files) {
      const lower = file.toLowerCase();
      if (lower.includes("instagram") && (lower.endsWith(".json") || lower.endsWith(".txt"))) {
        const content = await readFile(path.join(process.cwd(), file), "utf-8");
        if (lower.endsWith(".json")) {
          try {
            const parsed = JSON.parse(content);
            if (Array.isArray(parsed)) {
              instagramCookies.push(...parsed);
            }
          } catch {}
        } else {
          // Netscape parser
          const lines = content.split("\n");
          for (const line of lines) {
            if (line.startsWith("#") || !line.trim()) continue;
            const parts = line.split("\t");
            if (parts.length >= 7) {
              const domain = parts[0];
              const name = parts[5];
              const value = parts[6]?.trim() || "";
              if (domain.includes("instagram.com")) {
                instagramCookies.push({ name, value, domain });
              }
            }
          }
        }
      }
    }
  } catch (e) {
    console.error("Error scanning local files for Instagram cookies:", e);
  }

  // Also fall back to general local cookie files if no specific instagram ones found
  if (instagramCookies.length === 0) {
    try {
      const files = await readdir(process.cwd());
      for (const file of files) {
        const lower = file.toLowerCase();
        if ((lower.endsWith("cookies.json") || lower.endsWith("cookie.json")) && !lower.includes("youtube")) {
          const content = await readFile(path.join(process.cwd(), file), "utf-8");
          try {
            const parsed = JSON.parse(content);
            if (Array.isArray(parsed)) {
              const filtered = parsed.filter(c => c.domain && c.domain.includes("instagram.com"));
              instagramCookies.push(...filtered);
            }
          } catch {}
        }
      }
    } catch {}
  }
  
  if (instagramCookies.length > 0) {
    // Deduplicate by name
    const unique = [];
    const seen = new Set();
    for (const c of instagramCookies) {
      if (!seen.has(c.name)) {
        seen.add(c.name);
        unique.push(`${c.name}=${c.value}`);
      }
    }
    return unique.join("; ");
  }
  
  return "";
}

async function fetchInstagramMediaInfo(shortcode) {
  const mediaId = shortcodeToId(shortcode);
  
  // Endpoints to try in order of reliability
  const urls = [
    `https://www.instagram.com/api/v1/media/${mediaId}/info/`,
    `https://i.instagram.com/api/v1/media/${mediaId}/info/`,
    `https://www.instagram.com/p/${shortcode}/?__a=1&__d=dis`
  ];

  const cookieString = await getInstagramCookieString();
  const headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "X-IG-App-ID": "936619743392459",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin"
  };
  if (cookieString) {
    headers["Cookie"] = cookieString;
  } else {
    console.warn("fetchInstagramMediaInfo: No Instagram cookies found. Request may fail.");
  }

  const isHuggingFace = Boolean(process.env.SPACE_ID || process.env.SPACE_HOST);

  // Step 1: Try native fetch (skip on Hugging Face — Node.js fetch always times out there)
  if (!isHuggingFace) {
    for (const url of urls) {
      console.log(`fetchInstagramMediaInfo: Trying native fetch: ${url}`);
      try {
        const res = await fetch(url, { headers, signal: AbortSignal.timeout(6000) });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        const item = data.items?.[0] || data.graphql?.shortcode_media;
        if (item) return item;
        throw new Error("No media items returned.");
      } catch (e) {
        console.warn(`fetchInstagramMediaInfo: Native fetch failed for ${url}:`, e.message);
      }
    }
  } else {
    console.log("fetchInstagramMediaInfo: Hugging Face environment detected — skipping native fetch (known to timeout).");
  }

  // Step 2: Python urllib fallback (uses the same networking stack as yt-dlp)
  // On Hugging Face, Node.js fetch and curl both get ConnectTimeoutError to instagram.com,
  // but yt-dlp (Python/urllib) connects successfully. So we use Python as our HTTP client.
  console.log("fetchInstagramMediaInfo: All native fetch attempts failed. Trying Python urllib fallback...");

  for (const url of urls) {
    console.log(`fetchInstagramMediaInfo: Trying Python urllib for: ${url}`);
    try {
      const headersJson = JSON.stringify(headers);
      // Inline Python script that uses urllib.request (same stack as yt-dlp)
      const pyScript = `
import urllib.request, json, sys, ssl
ctx = ssl.create_default_context()
headers = json.loads(sys.argv[1])
req = urllib.request.Request(sys.argv[2], headers=headers)
try:
    resp = urllib.request.urlopen(req, timeout=8, context=ctx)
    sys.stdout.write(resp.read().decode('utf-8'))
except Exception as e:
    sys.stderr.write(str(e))
    sys.exit(1)
`.trim();

      const { stdout, stderr } = await execFileAsync("python3", ["-c", pyScript, headersJson, url], {
        timeout: 12000,
        maxBuffer: 5 * 1024 * 1024
      });

      if (!stdout || !stdout.trim()) {
        throw new Error(stderr ? `Python error: ${stderr.trim()}` : "Python returned empty response.");
      }

      const data = JSON.parse(stdout);
      const item = data.items?.[0] || data.graphql?.shortcode_media;
      if (item) {
        console.log("fetchInstagramMediaInfo: Python urllib succeeded!");
        return item;
      }
      throw new Error("No media items in Python response.");
    } catch (pyError) {
      console.error(`fetchInstagramMediaInfo: Python urllib failed for ${url}:`, pyError.message);
    }
  }

  throw new Error("All Instagram API fetch strategies (native fetch + Python urllib) failed for all endpoints.");
}

function parseInstagramMediaInfo(item, sourceUrl) {
  const title = sanitizeFilename(
    item.caption?.text?.split("\n")[0] || `Instagram post by ${item.user?.username || "user"}`,
    "Instagram Post"
  );
  const uploader = item.user?.full_name || item.user?.username || null;
  const description = item.caption?.text || null;
  const thumbnail = item.image_versions2?.candidates?.[0]?.url || null;

  const formats = [];
  
  if (item.media_type === 8) { // Carousel
    item.carousel_media?.forEach((m, idx) => {
      const isVideo = m.media_type === 2;
      const slideNum = idx + 1;
      if (isVideo) {
        const videoUrl = m.video_versions?.[0]?.url;
        if (videoUrl) {
          formats.push({
            id: `photo:carousel_${idx}_video:direct`,
            selector: videoUrl,
            thumbnail: m.image_versions2?.candidates?.[0]?.url,
            mode: "direct",
            type: "video",
            ext: "mp4",
            container: "VIDEO",
            label: `Slide ${slideNum} (Video)`,
            note: "High quality video slide",
            qualityValue: 1000 - idx,
            sizeBytes: 0,
            sizeLabel: "Unknown",
            requiresServerSupport: false
          });
        }
      } else {
        const imageUrl = m.image_versions2?.candidates?.[0]?.url;
        if (imageUrl) {
          formats.push({
            id: `photo:carousel_${idx}_image:direct`,
            selector: imageUrl,
            thumbnail: imageUrl,
            mode: "direct",
            type: "video",
            ext: "jpg",
            container: "IMAGE",
            label: `Slide ${slideNum} (Image)`,
            note: "High quality image slide",
            qualityValue: 1000 - idx,
            sizeBytes: 0,
            sizeLabel: "Unknown",
            requiresServerSupport: false
          });
        }
      }
    });
  } else if (item.media_type === 2) {
    const videoUrl = item.video_versions?.[0]?.url;
    if (videoUrl) {
      formats.push({
        id: `photo:video:direct`,
        selector: videoUrl,
        thumbnail: item.image_versions2?.candidates?.[0]?.url,
        mode: "direct",
        type: "video",
        ext: "mp4",
        container: "VIDEO",
        label: "Video (High Quality)",
        note: "High quality video",
        qualityValue: 1000,
        sizeBytes: 0,
        sizeLabel: "Unknown",
        requiresServerSupport: false
      });
    }
  } else {
    const imageUrl = item.image_versions2?.candidates?.[0]?.url;
    if (imageUrl) {
      formats.push({
        id: `photo:image:direct`,
        selector: imageUrl,
        thumbnail: imageUrl,
        mode: "direct",
        type: "video",
        ext: "jpg",
        container: "IMAGE",
        label: "Image (High Quality)",
        note: "High quality image",
        qualityValue: 1000,
        sizeBytes: 0,
        sizeLabel: "Unknown",
        requiresServerSupport: false
      });
    }
  }

  const videoGroupsMap = new Map();
  formats.forEach(format => {
    const container = format.container;
    if (!videoGroupsMap.has(container)) {
      videoGroupsMap.set(container, {
        container,
        type: "video",
        items: []
      });
    }
    videoGroupsMap.get(container).items.push(format);
  });

  const videoGroups = Array.from(videoGroupsMap.values());

  return {
    sourceUrl,
    title,
    description: description ? description.slice(0, 180) : null,
    thumbnail,
    sourceName: "Instagram",
    durationLabel: "Unknown",
    durationSeconds: 0,
    uploader,
    uploadDate: null,
    formats,
    formatGroups: {
      video: videoGroups,
      audio: []
    },
    serverWarning: ""
  };
}

export async function inspectMedia(sourceUrl) {
  let stdout, stderr;
  const isYouTube = sourceUrl && (sourceUrl.includes("youtube.com") || sourceUrl.includes("youtu.be"));
  
  let attempts = [];
  if (isYouTube) {
    const hasCookies = await hasCookiesConfigured();
    if (hasCookies) {
      // 1. Forced Cookies, Default (High Quality)
      attempts.push({ useCookies: true, usePlayerClient: false, name: "Forced Cookies, Default" });
      // 2. Forced Cookies, Safe Fallback (Reliable Bot Bypass with Cookies)
      attempts.push({ useCookies: true, usePlayerClient: true, name: "Forced Cookies, Safe Fallback" });
      // 3. Anonymous, Default (High Quality Fallback)
      attempts.push({ useCookies: false, usePlayerClient: false, name: "Anonymous, Default" });
      // 4. Anonymous, Safe Fallback (Low Quality, Bot Bypass)
      attempts.push({ useCookies: false, usePlayerClient: true, name: "Anonymous, Safe Fallback" });
    } else {
      // 1. Anonymous, Default (High Quality)
      attempts.push({ useCookies: false, usePlayerClient: false, name: "Anonymous, Default" });
      // 2. Anonymous, Safe Fallback (Low Quality, Bot Bypass)
      attempts.push({ useCookies: false, usePlayerClient: true, name: "Anonymous, Safe Fallback" });
    }
  } else {
    // Non-YouTube URLs run with default cookies, no player-client
    attempts.push({ useCookies: false, usePlayerClient: false, name: "Default" });
  }

  let lastError = null;

  for (let i = 0; i < attempts.length; i++) {
    const attempt = attempts[i];
    
    // Skip forcing cookies attempt if we don't have cookies available.
    const cookiesArg = await getCookiesArg(sourceUrl, attempt.useCookies);
    if (attempt.useCookies && cookiesArg.length === 0) {
      console.log(`inspectMedia: Skipping attempt '${attempt.name}' because no cookies are configured.`);
      continue;
    }

    const isAnonymous = !attempt.useCookies;
    const socketTimeout = isAnonymous ? "4" : "8";
    const execTimeout = isAnonymous ? 5000 : 10000;

    console.log(`inspectMedia: Trying attempt '${attempt.name}' (Cookies: ${cookiesArg.length > 0 ? "Yes" : "No"}, Player Client: ${attempt.usePlayerClient}, Timeout: ${execTimeout}ms)`);
    
    const args = ["--ignore-config", "--geo-bypass", "--no-warnings", "--js-runtimes", "node", "--socket-timeout", socketTimeout];
    if (attempt.usePlayerClient) {
      args.push("--extractor-args", "youtube:player-client=web,mweb,android");
    }
    args.push(...cookiesArg, "--dump-single-json", "--no-playlist", "--skip-download", sourceUrl);

    try {
      const result = await execFileAsync(YT_DLP_BIN, args, { 
        maxBuffer: 20 * 1024 * 1024,
        timeout: execTimeout
      });
      stdout = result.stdout;
      stderr = result.stderr;

      // If YouTube and resolved formats are only <= 360p, retry with a better configuration (if available).
      if (isYouTube && i < attempts.length - 1) {
        try {
          const info = JSON.parse(stdout);
          const rawFormats = info.formats || [];
          const hasHighQuality = rawFormats.some(f => f.vcodec !== "none" && (f.height || 0) > 360);
          
          if (!hasHighQuality) {
            console.log(`inspectMedia: Attempt '${attempt.name}' succeeded but returned only low quality (<=360p) formats. Retrying with next attempt...`);
            continue; // Go to next attempt
          }
        } catch (e) {
          // If JSON parse fails, let it fall through
        }
      }

      // If we got here, we successfully resolved the media with acceptable quality (or have no more options).
      break;
    } catch (error) {
      console.error(`inspectMedia: Attempt '${attempt.name}' failed:`, error.stderr?.trim() || error.message);
      lastError = error;
      
      if (error.code === "ENOENT") {
        throw createYtError("yt-dlp is not installed on this server yet. Install yt-dlp and ffmpeg first.", 503);
      }
      
      // If it's the last attempt, let it exit loop and throw
      if (i === attempts.length - 1) {
        break;
      }
    }
  }

  if (isYouTube) {
    if (stdout) {
      resetYoutubeFailures();
    } else {
      incrementYoutubeFailures();
    }
  }

  if (!stdout) {
    const isInstagram = sourceUrl && (sourceUrl.includes("instagram.com") || sourceUrl.includes("instagr.am"));
    if (isInstagram) {
      console.log("inspectMedia: yt-dlp failed on Instagram link. Attempting Instagram API fallback...");
      try {
        const shortcodeMatch = sourceUrl.match(/(?:p|reel|tv)\/([A-Za-z0-9-_]+)/);
        if (shortcodeMatch) {
          const shortcode = shortcodeMatch[1];
          const item = await fetchInstagramMediaInfo(shortcode);
          return parseInstagramMediaInfo(item, sourceUrl);
        }
      } catch (fallbackError) {
        console.error("inspectMedia: Instagram API fallback failed:", fallbackError.stack || fallbackError.message, fallbackError.cause);
      }
    }

    const errText = lastError?.stderr?.trim() || lastError?.message || "This link could not be inspected right now.";
    if (isYouTube) {
      throw createYtError(
        "YouTube is temporarily rate-limiting the server. We are automatically rotating our connection IP right now. Please wait 1–2 minutes and try pasting your link again.",
        403
      );
    }
    if (errText.includes("No video formats found") && (sourceUrl.includes("instagram.com") || sourceUrl.includes("instagr.am"))) {
      throw createYtError(
        "This Instagram link contains only photos/images. Downloader by The Atom only supports downloading videos (like Reels and video posts) or audio.",
        400
      );
    }
    throw createYtError(errText, 400);
  }

  try {
    const info = JSON.parse(stdout);

    // For formats that have a direct URL but no filesize or bitrate info (common with
    // Instagram progressive streams), make parallel HEAD requests to get Content-Length.
    // Runs in parallel with a 3-second timeout per request so it adds minimal latency.
    const rawFormats = info.formats || [];
    const missingSize = rawFormats.filter(
      (f) => f.url && !f.filesize && !f.filesize_approx && !(f.tbr || f.vbr || f.abr)
    );

    if (missingSize.length > 0) {
      await Promise.allSettled(
        missingSize.map(async (f) => {
          try {
            const res = await fetch(f.url, {
              method: "HEAD",
              signal: AbortSignal.timeout(3000),
              headers: {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
              }
            });
            const len = parseInt(res.headers.get("content-length") || "0", 10);
            if (len > 0) {
              f.filesize = len; // Mutate in place — picked up by estimateSizeBytes
            }
          } catch {
            // Silently ignore — size stays "Unknown" if HEAD fails
          }
        })
      );
    }

    const baseFormats = normalizeFormats(info);
    const serverWarning = normalizeWarningText(stderr);
    const formats = applyServerAvailability(baseFormats, {
      serverWarning,
      sourceUrl,
      sourceName: info.extractor_key || info.extractor || info.webpage_url_domain || ""
    });
    const title = sanitizeFilename(info.title || "Untitled media", "Untitled media");

    return {
      sourceUrl,
      title,
      description: info.description ? info.description.slice(0, 180) : null,
      thumbnail: info.thumbnail || info.thumbnails?.at?.(-1)?.url || null,
      sourceName: formatSourceName(info.extractor_key || info.extractor || info.webpage_url_domain || ""),
      durationLabel: formatDurationSeconds(info.duration),
      durationSeconds: info.duration || 0,
      uploader: info.uploader || info.channel || info.creator || null,
      uploadDate: info.upload_date || null,
      formats: formats.flat,
      formatGroups: {
        video: formats.video,
        audio: formats.audio
      },
      serverWarning
    };
  } catch (error) {
    if (error.statusCode) throw error;
    throw createYtError(error.message || "This link could not be inspected right now.", 400);
  }
}

function buildDownloadArgs({ sourceUrl, selector, mode, ext, outputTemplate, recode = false, usePlayerClient = true }) {
  const args = ["--ignore-config", "--geo-bypass", "--js-runtimes", "node", "--no-warnings", "--no-playlist"];
  if (usePlayerClient) {
    args.push("--extractor-args", "youtube:player-client=web,mweb,android");
  }

  // Optimize download performance by writing directly to final file & skipping unnecessary disk/metadata tasks
  args.push("--no-part", "--no-mtime", "--no-embed-metadata", "--no-embed-thumbnail");

  if (mode === "extract-audio") {
    args.push(
      "-f",
      selector || "bestaudio/best",
      "-x",
      "--audio-format",
      normalizeExt(ext, "mp3"),
      "--audio-quality",
      "0",
      "-o",
      outputTemplate,
      sourceUrl
    );

    return args;
  }

  args.push("-f", selector || "best");

  if (mode === "merge") {
    args.push("--merge-output-format", normalizeExt(ext, "mp4"));

    if (recode) {
      // VP9/AV1 codecs don't play on macOS QuickTime or iOS natively.
      // Re-encode to H.264 using a fast preset so the file works everywhere.
      // -c:a copy preserves audio quality without re-encoding.
      args.push(
        "--postprocessor-args",
        "Merger+ffmpeg:-c:v libx264 -crf 23 -preset veryfast -c:a copy"
      );
    }
  }

  args.push("-o", outputTemplate, sourceUrl);
  return args;
}

function buildDownloadError(stderr = "") {
  const lower = stderr.toLowerCase();

  if (lower.includes("http error 403") || lower.includes("po token") || lower.includes("sabr")) {
    return createYtError(
      "This quality needs a newer yt-dlp build or extra YouTube server support before it can download reliably. Update yt-dlp first, then try again.",
      409
    );
  }

  return createYtError(stderr || "The download could not be prepared.", 500);
}

async function createTempOutputDir() {
  const dir = path.join(TMP_ROOT, createTempId());
  await mkdir(dir, { recursive: true });
  return dir;
}

async function locateCompletedFile(directoryPath) {
  const entries = await readdir(directoryPath, { withFileTypes: true });
  const files = entries
    .filter((entry) => entry.isFile() && !entry.name.endsWith(".part"))
    .map((entry) => path.join(directoryPath, entry.name));

  if (!files.length) {
    throw createYtError("The server could not find the finished media file.", 500);
  }

  return files[0];
}

export async function streamDownloadDirect({ sourceUrl, selector, ext }) {
  const isDirectUrl = selector && (selector.startsWith("http://") || selector.startsWith("https://"));
  
  if (isDirectUrl) {
    const res = await fetch(selector, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      }
    });
    if (!res.ok) {
      throw new Error(`Failed to fetch direct stream: status ${res.status}`);
    }
    return res.body;
  }

  const hasCookies = await hasCookiesConfigured();
  const cookiesArg = await getCookiesArg(sourceUrl, hasCookies);
  const args = ["--ignore-config", "--geo-bypass", "--js-runtimes", "node", "--no-warnings", "--no-playlist"];
  
  const isYouTube = sourceUrl && (sourceUrl.includes("youtube.com") || sourceUrl.includes("youtu.be"));
  if (isYouTube) {
    args.push("--extractor-args", "youtube:player-client=web,mweb,android");
  }
  
  args.push("-f", selector || "best", "-o", "-", sourceUrl);
  args.unshift(...cookiesArg);

  const child = spawn(YT_DLP_BIN, args, {
    stdio: ["ignore", "pipe", "pipe"]
  });

  const stderrChunks = [];
  child.stderr.on("data", (chunk) => {
    stderrChunks.push(chunk);
  });

  return new ReadableStream({
    start(controller) {
      child.stdout.on("data", (chunk) => {
        controller.enqueue(new Uint8Array(chunk));
      });

      child.stdout.on("end", () => {
        if (child.exitCode !== null && child.exitCode !== 0) {
          const stderr = Buffer.concat(stderrChunks).toString().trim();
          console.error(`yt-dlp stream exited with code ${child.exitCode}: ${stderr}`);
        }
        controller.close();
      });

      child.stdout.on("error", (error) => {
        controller.error(error);
        child.kill();
      });
    },
    cancel() {
      child.kill();
    }
  });
}

export async function prepareDownloadFile({ sourceUrl, selector, mode, ext, downloadId, recode = false }) {
  const isDirectUrl = selector && (selector.startsWith("http://") || selector.startsWith("https://"));
  
  if (isDirectUrl) {
    const outputDir = await createTempOutputDir();
    const title = sourceUrl.includes("instagram.com") ? "Instagram_Post" : "download";
    const filename = `${title}.${ext}`;
    const filePath = path.join(outputDir, filename);

    if (downloadId) {
      activeDownloads.set(downloadId, { status: "downloading", progress: 0 });
    }

    try {
      const response = await fetch(selector, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        }
      });
      if (!response.ok) {
        throw new Error(`Failed to fetch direct media: status ${response.status}`);
      }

      const arrayBuffer = await response.arrayBuffer();
      await writeFile(filePath, Buffer.from(arrayBuffer));

      const cleanup = async () => {
        await rm(outputDir, { recursive: true, force: true }).catch(() => null);
      };

      if (downloadId) {
        activeDownloads.set(downloadId, {
          status: "completed",
          progress: 100,
          filePath,
          cleanup
        });

        // Auto-cleanup after 5 minutes if client never fetches it
        setTimeout(async () => {
          const entry = activeDownloads.get(downloadId);
          if (entry && entry.filePath === filePath) {
            try {
              await cleanup();
            } catch (e) {
              console.error("Auto-cleanup failed:", e);
            }
            activeDownloads.delete(downloadId);
          }
        }, 5 * 60 * 1000);
      }

      return {
        filePath,
        cleanup
      };
    } catch (err) {
      if (downloadId) {
        activeDownloads.set(downloadId, { status: "failed", error: err.message || "Failed" });
      }
      await rm(outputDir, { recursive: true, force: true }).catch(() => null);
      throw err;
    }
  }

  const outputDir = await createTempOutputDir();
  const outputTemplate = path.join(outputDir, "%(title)s.%(ext)s");

  const runDownload = async (useCookiesForce, usePlayerClient = true) => {
    const args = buildDownloadArgs({
      sourceUrl,
      selector,
      mode,
      ext,
      outputTemplate,
      recode,
      usePlayerClient
    });

    const cookiesArg = await getCookiesArg(sourceUrl, useCookiesForce);
    args.unshift(...cookiesArg);

    if (downloadId) {
      activeDownloads.set(downloadId, { status: "downloading", progress: 0 });
    }

    const child = spawn(YT_DLP_BIN, args, {
      stdio: ["ignore", "pipe", "pipe"]
    });

    let downloadCount = 0;
    const seenFiles = new Set();

    child.stdout.on("data", (chunk) => {
      // yt-dlp writes progress with \r between updates — split on both \r and \n
      const text = chunk.toString();
      const lines = text.split(/[\r\n]+/);
      for (const line of lines) {
        if (line.includes("[Merger]") || line.includes("Merging formats") || line.includes("[ExtractAudio]") || line.includes("ffmpeg")) {
          if (downloadId) {
            activeDownloads.set(downloadId, { status: "merging", progress: 99 });
          }
        }

        const destMatch = line.match(/\[download\]\s+Destination:\s+(.+)$/) || line.match(/\[download\]\s+(.+?)\s+has already been downloaded/);
        if (destMatch) {
          const filePath = destMatch[1].trim();
          if (!seenFiles.has(filePath)) {
            seenFiles.add(filePath);
            downloadCount = seenFiles.size;
          }
        }

        const match = line.match(/\[download\]\s+(\d+(?:\.\d+)?)%/);
        if (match && downloadId) {
          const percent = parseFloat(match[1]);
          const current = activeDownloads.get(downloadId);

          let lastPercent = current?.lastPercent || 0;
          let currentDownloadNum = current?.downloadNum || 1;

          // Heuristic to detect second stream download (e.g. video finished at >80% and audio restarts at <20%)
          if (percent < 20 && lastPercent > 80) {
            currentDownloadNum = 2;
          }

          let progress = percent;
          if (mode === "merge") {
            // In merge mode, there are 2 downloads: video (first) and audio (second).
            // We map the first download (video) to 0% - 85%
            // and the second download (audio) to 85% - 98%.
            if (downloadCount > 1 || currentDownloadNum > 1) {
              progress = 85 + (percent * 0.13);
              currentDownloadNum = 2; // ensure persist
            } else {
              progress = percent * 0.85;
            }
          } else {
            // Cap direct downloading progress at 95% to avoid displaying 100%
            // before the process has exited and the file is actually ready.
            progress = percent * 0.95;
          }

          // Strict caps during downloading phase to prevent showing 100% prematurely
          const maxDownloadingProgress = mode === "merge" ? 98 : 95;
          if (progress > maxDownloadingProgress) {
            progress = maxDownloadingProgress;
          }

          // Only update if progress is moving forward or status changed/reset
          if (!current || current.progress < progress || current.status !== "downloading") {
            activeDownloads.set(downloadId, {
              status: "downloading",
              progress,
              lastPercent: percent,
              downloadNum: currentDownloadNum
            });
          }
        }
      }
    });

    const stderrChunks = [];
    child.stderr.on("data", (chunk) => {
      const text = chunk.toString();
      stderrChunks.push(Buffer.from(chunk));

      if (downloadId && (text.includes("[Merger]") || text.includes("Merging formats") || text.includes("ffmpeg"))) {
        activeDownloads.set(downloadId, { status: "merging", progress: 99 });
      }
    });

    const exitCode = await new Promise((resolve, reject) => {
      child.once("error", (error) => {
        if (downloadId) {
          activeDownloads.set(downloadId, { status: "failed", error: error.message || "Failed" });
        }
        if (error.code === "ENOENT") {
          reject(createYtError("yt-dlp is not installed on this server yet. Install yt-dlp and ffmpeg first.", 503));
          return;
        }

        reject(createYtError(error.message || "The download process could not start.", 500));
      });

      child.once("close", resolve);
    });

    if (exitCode !== 0) {
      const stderr = Buffer.concat(stderrChunks).toString("utf8").trim();
      throw createYtError(stderr, exitCode);
    }
  };

  const isYouTube = sourceUrl && (sourceUrl.includes("youtube.com") || sourceUrl.includes("youtu.be"));
  const hasCookies = isYouTube && (await hasCookiesConfigured());

  let downloadSucceeded = false;
  let lastDownloadError = null;

  if (hasCookies) {
    console.log("prepareDownloadFile: Cookies configured, prioritizing forced cookies HQ download...");
    try {
      await runDownload(true, false);
      downloadSucceeded = true;
    } catch (error) {
      console.error("prepareDownloadFile: Prioritized forced cookies HQ attempt failed. Trying safe fallback with cookies...", error.message);
      lastDownloadError = error;
      try {
        await runDownload(true, true);
        downloadSucceeded = true;
      } catch (cookieFallbackError) {
        console.error("prepareDownloadFile: Forced cookies safe fallback attempt failed. Retrying anonymously...", cookieFallbackError.message);
        lastDownloadError = cookieFallbackError;
        try {
          await runDownload(false, false);
          downloadSucceeded = true;
        } catch (retryError) {
          lastDownloadError = retryError;
        }
      }
    }
  } else {
    try {
      await runDownload(false, false);
      downloadSucceeded = true;
    } catch (error) {
      lastDownloadError = error;
      if (isYouTube) {
        console.log("prepareDownloadFile: Anonymous HQ download failed. Checking forced cookies HQ...");
        const cookiesArgForced = await getCookiesArg(sourceUrl, true);
        if (cookiesArgForced.length > 0) {
          try {
            await runDownload(true, false);
            downloadSucceeded = true;
          } catch (retryError) {
            console.error("prepareDownloadFile: Forced cookies HQ attempt failed. Trying safe fallback with cookies...", retryError.message);
            lastDownloadError = retryError;
            try {
              await runDownload(true, true);
              downloadSucceeded = true;
            } catch (cookieFallbackError) {
              console.error("prepareDownloadFile: Forced cookies safe fallback attempt failed:", cookieFallbackError.message);
              lastDownloadError = cookieFallbackError;
            }
          }
        }
      }
    }
  }

  if (isYouTube && !downloadSucceeded) {
    console.log("prepareDownloadFile: HQ attempts failed/skipped. Trying Safe Fallback with player-client...");
    try {
      await runDownload(false, true);
      downloadSucceeded = true;
    } catch (fallbackError) {
      console.error("prepareDownloadFile: Safe Fallback attempt failed:", fallbackError.message);
      lastDownloadError = fallbackError;
    }
  }

  if (!downloadSucceeded) {
    if (downloadId) {
      activeDownloads.set(downloadId, { status: "failed", error: "Process exited with non-zero code" });
    }
    await rm(outputDir, { recursive: true, force: true }).catch(() => null);
    throw buildDownloadError(lastDownloadError?.message || "The download could not be completed.");
  }

  const filePath = await locateCompletedFile(outputDir);
  const cleanup = async () => {
    await rm(outputDir, { recursive: true, force: true }).catch(() => null);
  };

  if (downloadId) {
    activeDownloads.set(downloadId, {
      status: "completed",
      progress: 100,
      filePath,
      cleanup
    });

    // Auto-cleanup after 5 minutes if client never fetches it
    setTimeout(async () => {
      const entry = activeDownloads.get(downloadId);
      if (entry && entry.filePath === filePath) {
        try {
          await cleanup();
        } catch (e) {
          console.error("Auto-cleanup failed:", e);
        }
        activeDownloads.delete(downloadId);
      }
    }, 5 * 60 * 1000);
  }

  return {
    filePath,
    cleanup
  };
}

export function getDownloadHeaders({ filename, ext, size }) {
  const safeName = sanitizeFilename(filename, "download");
  const finalExt = normalizeExt(ext, "mp4");

  const headers = {
    "Cache-Control": "no-store",
    "Content-Type": guessMimeType(finalExt),
    "Content-Disposition": `attachment; filename*=UTF-8''${encodeURIComponent(`${safeName}.${finalExt}`)}`
  };

  if (size && size > 0) {
    headers["Content-Length"] = String(size);
  }

  return headers;
}

export function createReadableStreamFromFile(filePath, onFinish) {
  const nodeStream = createReadStream(filePath);

  return new ReadableStream({
    start(controller) {
      nodeStream.on("data", (chunk) => {
        controller.enqueue(new Uint8Array(chunk));
      });

      nodeStream.on("end", async () => {
        controller.close();
        if (onFinish) {
          await onFinish(true);
        }
      });

      nodeStream.on("error", async (error) => {
        controller.error(error);
        if (onFinish) {
          await onFinish(false);
        }
      });
    },
    async cancel() {
      nodeStream.destroy();
      if (onFinish) {
        await onFinish(false);
      }
    }
  });
}

// Register a proactive canary connection checker to verify YouTube access.
// If it fails twice consecutively, increment consecutive failures to trigger IP rotation.
jobManager.registerCanaryChecker(async () => {
  const checkOne = await runCanaryCheck();
  if (checkOne) {
    resetYoutubeFailures();
    return;
  }

  console.warn("ytDlp: Proactive canary check failed. Retrying in 15 seconds to filter transient hiccups...");
  await new Promise((resolve) => setTimeout(resolve, 15000));

  const checkTwo = await runCanaryCheck();
  if (checkTwo) {
    resetYoutubeFailures();
    return;
  }

  console.warn("ytDlp: Double proactive canary checks failed. Server IP block or invalid cookies detected.");
  incrementYoutubeFailures();
});

async function runCanaryCheck() {
  try {
    // Rick Astley - Never Gonna Give You Up (official stable video)
    const result = await inspectMedia("https://www.youtube.com/watch?v=dQw4w9WgXcQ");
    return Boolean(result && result.formats && result.formats.length > 0);
  } catch (err) {
    console.warn("ytDlp: Canary inspect attempt failed:", err.message);
    return false;
  }
}

