import os from "node:os";
import path from "node:path";
import { createReadStream, existsSync } from "node:fs";
import { execFile, spawn } from "node:child_process";
import { mkdir, readdir, rm, writeFile, readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { promisify } from "node:util";
import {
  formatBytes,
  formatDurationSeconds,
  formatSourceName,
  sanitizeFilename
} from "@/utils/helpers";

const execFileAsync = promisify(execFile);
const YT_DLP_BIN = process.env.YT_DLP_BIN || "yt-dlp";
const TMP_ROOT = path.join(os.tmpdir(), "fetch-by-the-atom");
const ALLOW_YOUTUBE_ADAPTIVE = process.env.ALLOW_YOUTUBE_ADAPTIVE !== "false";
export const activeDownloads = new Map();

function convertJsonToNetscape(jsonContent) {
  let cookies;
  try {
    cookies = JSON.parse(jsonContent);
  } catch (e) {
    throw new Error("Failed to parse JSON cookie content: " + e.message);
  }

  // Check if it's the encrypted/internal backup format of Hotcleaner Cookie-Editor
  if (cookies && !Array.isArray(cookies) && typeof cookies === "object" && cookies.data) {
    throw new Error(
      "The provided cookies.json file is an encrypted Cookie-Editor backup. Please export your cookies as 'JSON' or 'Netscape' from the extension instead of creating a 'Backup' file."
    );
  }

  if (!Array.isArray(cookies)) {
    throw new Error("JSON cookies must be a JSON array of cookie objects.");
  }

  let output = "# Netscape HTTP Cookie File\n# This file was generated by fetch-by-the-atom converter\n\n";

  for (const cookie of cookies) {
    if (!cookie.name || !cookie.domain) {
      continue;
    }
    const domain = cookie.domain;
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const path = cookie.path || "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    
    let expiration = 0;
    if (typeof cookie.expirationDate === "number") {
      expiration = Math.round(cookie.expirationDate);
    } else if (typeof cookie.expiry === "number") {
      expiration = Math.round(cookie.expiry);
    }
    
    const name = cookie.name;
    const value = cookie.value || "";

    output += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
  }

  return output;
}

let lastProcessedBase64 = null;

async function getCookiesArg() {
  const tmpTxtPath = path.join(os.tmpdir(), "fetch-by-the-atom-cookies.txt");
  
  console.log("getCookiesArg: Checking cookies configuration...");
  // 1. Decode/convert from environment variable if available
  if (process.env.YT_DLP_COOKIES_BASE64) {
    const rawLen = process.env.YT_DLP_COOKIES_BASE64.length;
    console.log(`getCookiesArg: YT_DLP_COOKIES_BASE64 env var found. Length: ${rawLen}`);
    if (process.env.YT_DLP_COOKIES_BASE64 !== lastProcessedBase64 || !existsSync(tmpTxtPath)) {
      try {
        const cleanBase64 = process.env.YT_DLP_COOKIES_BASE64.replace(/\s/g, "");
        console.log(`getCookiesArg: Cleaned base64 length: ${cleanBase64.length}`);
        const decoded = Buffer.from(cleanBase64, "base64").toString("utf-8").trim();
        console.log(`getCookiesArg: Decoded string length: ${decoded.length}`);
        let netscapeContent = decoded;
        
        const isJson = decoded.startsWith("[") || decoded.startsWith("{");
        console.log(`getCookiesArg: Decoded content is JSON: ${isJson}`);
        if (isJson) {
          netscapeContent = convertJsonToNetscape(decoded);
          console.log("getCookiesArg: Successfully converted JSON to Netscape format.");
        }
        
        await writeFile(tmpTxtPath, netscapeContent, "utf-8");
        lastProcessedBase64 = process.env.YT_DLP_COOKIES_BASE64;
      } catch (e) {
        console.error("getCookiesArg: Failed to process YT_DLP_COOKIES_BASE64:", e);
        throw new Error(`Failed to process environment cookies: ${e.message}`);
      }
    }
    
    if (existsSync(tmpTxtPath)) {
      console.log("getCookiesArg: Using environment cookies file.");
      return ["--cookies", tmpTxtPath];
    }
  } else {
    console.log("getCookiesArg: YT_DLP_COOKIES_BASE64 env var NOT found.");
  }
  
  // 2. Check for local cookie files (JSON preferred, then Netscape txt)
  let localFiles = [];
  try {
    const files = await readdir(process.cwd());
    for (const file of files) {
      const lower = file.toLowerCase();
      if (lower.endsWith("cookies.json") || lower.endsWith("cookie.json")) {
        localFiles.push({ path: path.join(process.cwd(), file), isJson: true, name: file, priority: 1 });
      } else if (lower.endsWith("cookies.txt") || lower.endsWith("cookie.txt")) {
        localFiles.push({ path: path.join(process.cwd(), file), isJson: false, name: file, priority: 2 });
      }
    }
    // Sort so JSON files are processed before TXT files
    localFiles.sort((a, b) => a.priority - b.priority);
  } catch (e) {
    console.error("Failed to read local directory for cookies:", e);
  }
  
  let lastError = null;
  for (const item of localFiles) {
    if (existsSync(item.path)) {
      try {
        const content = await readFile(item.path, "utf-8");
        const trimmed = content.trim();
        const isJson = trimmed.startsWith("[") || trimmed.startsWith("{");
        
        if (isJson) {
          const converted = convertJsonToNetscape(trimmed);
          await writeFile(tmpTxtPath, converted, "utf-8");
          console.log(`Successfully converted and loaded cookies from local file: ${item.name}`);
          return ["--cookies", tmpTxtPath];
        } else {
          await writeFile(tmpTxtPath, content, "utf-8");
          console.log(`Successfully loaded cookies from local Netscape file: ${item.name}`);
          return ["--cookies", tmpTxtPath];
        }
      } catch (e) {
        console.error(`Failed to process local cookie file at ${item.path}:`, e.message);
        lastError = e;
      }
    }
  }
  
  if (lastError) {
    throw lastError;
  }
  
  // 3. Fallback to existing tmpTxtPath if neither env nor local files are found/valid
  if (existsSync(tmpTxtPath)) {
    return ["--cookies", tmpTxtPath];
  }
  
  return [];
}

function createYtError(message, statusCode = 500) {
  const error = new Error(message);
  error.statusCode = statusCode;
  return error;
}

function createTempId() {
  return randomUUID();
}

function guessMimeType(ext = "") {
  const normalized = ext.toLowerCase();

  if (normalized === "mp4" || normalized === "m4v") {
    return "video/mp4";
  }

  if (normalized === "webm") {
    return "video/webm";
  }

  if (normalized === "mp3") {
    return "audio/mpeg";
  }

  if (normalized === "m4a") {
    return "audio/mp4";
  }

  if (normalized === "jpg" || normalized === "jpeg") {
    return "image/jpeg";
  }

  if (normalized === "png") {
    return "image/png";
  }

  return "application/octet-stream";
}

function normalizeExt(ext = "", fallback = "mp4") {
  return String(ext || fallback).toLowerCase();
}

function isYouTubeLikeSource(value = "") {
  const normalized = String(value || "").toLowerCase();
  return normalized.includes("youtube") || normalized.includes("youtu.be");
}

function getCodecPriority(format) {
  const codec = String(format.vcodec || "").toLowerCase();

  if (codec.includes("avc") || codec.includes("h264")) {
    return 3;
  }

  if (codec.includes("vp9")) {
    return 2;
  }

  if (codec.includes("av01")) {
    return 1;
  }

  return 0;
}

function isPrimaryAudioTrack(format) {
  const note = String(format.format_note || "").toLowerCase();

  if (note.includes("drc")) {
    return false;
  }

  if (note.includes("original (default)")) {
    return true;
  }

  return !/-\d+$/.test(String(format.format_id || ""));
}

function pickBetterVideoFormat(current, next) {
  if (!current) {
    return next;
  }

  const currentProgressive = current.acodec !== "none";
  const nextProgressive = next.acodec !== "none";

  if (currentProgressive !== nextProgressive) {
    return nextProgressive ? next : current;
  }

  const currentCodec = getCodecPriority(current);
  const nextCodec = getCodecPriority(next);

  if (currentCodec !== nextCodec) {
    return nextCodec > currentCodec ? next : current;
  }

  return (next.tbr || 0) > (current.tbr || 0) ? next : current;
}

function sortByContainerThenQuality(groups = []) {
  return [...groups]
    .sort((first, second) => first.container.localeCompare(second.container))
    .map((group) => ({
      ...group,
      items: [...group.items].sort((first, second) => {
        if (first.type === "video") {
          return (second.qualityValue || 0) - (first.qualityValue || 0);
        }

        return (second.qualityValue || 0) - (first.qualityValue || 0);
      })
    }));
}

function buildVideoGroups(formats = []) {
  const bestPerVariant = new Map();

  for (const format of formats) {
    if (!format?.format_id || format.vcodec === "none" || !format.ext || format.ext === "mhtml") {
      continue;
    }

    const key = `${format.ext}:${format.height || 0}:${format.fps || 0}`;
    const current = bestPerVariant.get(key);
    bestPerVariant.set(key, pickBetterVideoFormat(current, format));
  }

  const grouped = new Map();

  for (const format of bestPerVariant.values()) {
    const progressive = format.acodec !== "none";
    const container = format.ext.toUpperCase();
    const resolution = format.height ? `${format.height}p` : format.format_note || "Video";
    const fps = format.fps ? `${format.fps}fps` : null;
    const mode = progressive ? "direct" : "merge";
    const note = progressive
      ? [resolution, fps, "ready with audio"].filter(Boolean).join(" • ")
      : [resolution, fps, "server merge required"].filter(Boolean).join(" • ");
    const option = {
      id: `video:${format.format_id}:${mode}`,
      selector: progressive ? format.format_id : `${format.format_id}+bestaudio/best`,
      mode,
      type: "video",
      isAdaptive: !progressive,
      ext: normalizeExt(format.ext, "mp4"),
      container,
      label: resolution,
      note,
      qualityValue: format.height || 0,
      sizeBytes: format.filesize || format.filesize_approx || 0,
      sizeLabel: formatBytes(format.filesize || format.filesize_approx || 0),
      requiresServerSupport: !progressive
    };

    if (!grouped.has(container)) {
      grouped.set(container, {
        container,
        type: "video",
        items: []
      });
    }

    grouped.get(container).items.push(option);
  }

  return sortByContainerThenQuality([...grouped.values()]);
}

function buildAudioGroups(formats = []) {
  const primaryFormats = formats.filter((format) => (
    format?.format_id &&
    format.vcodec === "none" &&
    format.acodec !== "none" &&
    format.ext &&
    format.ext !== "mhtml" &&
    isPrimaryAudioTrack(format)
  ));

  const grouped = new Map();

  for (const format of primaryFormats) {
    const container = format.ext.toUpperCase();
    const bitrate = Math.round(format.abr || format.tbr || 0);
    const option = {
      id: `audio:${format.format_id}:direct`,
      selector: format.format_id,
      mode: "direct",
      type: "audio",
      ext: normalizeExt(format.ext, "m4a"),
      container,
      label: bitrate ? `${bitrate}kbps` : "Audio",
      note: "Original audio track",
      qualityValue: bitrate,
      sizeBytes: format.filesize || format.filesize_approx || 0,
      sizeLabel: formatBytes(format.filesize || format.filesize_approx || 0),
      requiresServerSupport: false
    };

    if (!grouped.has(container)) {
      grouped.set(container, {
        container,
        type: "audio",
        items: []
      });
    }

    grouped.get(container).items.push(option);
  }

  const mp3Group = {
    container: "MP3",
    type: "audio",
    items: [
      {
        id: "audio:bestaudio:extract-mp3",
        selector: "bestaudio/best",
        mode: "extract-audio",
        type: "audio",
        isAdaptive: false,
        ext: "mp3",
        container: "MP3",
        label: "Best available",
        note: "Converted to MP3 on the server",
        qualityValue: 999,
        sizeBytes: 0,
        sizeLabel: "Unknown",
        requiresServerSupport: true
      }
    ]
  };

  return sortByContainerThenQuality([...grouped.values(), mp3Group]);
}

function normalizeFormats(info) {
  const video = buildVideoGroups(info.formats || []);
  const audio = buildAudioGroups(info.formats || []);
  const flat = [...video.flatMap((group) => group.items), ...audio.flatMap((group) => group.items)];

  if (!flat.length) {
    const fallback = {
      id: "video:best:direct",
      selector: "best",
      mode: "direct",
      type: "video",
      isAdaptive: false,
      ext: normalizeExt(info.ext, "mp4"),
      container: String(info.ext || "file").toUpperCase(),
      label: `Best available ${String(info.ext || "file").toUpperCase()}`,
      note: "Let the server pick the best direct format",
      qualityValue: 0,
      sizeBytes: 0,
      sizeLabel: "Unknown",
      requiresServerSupport: false
    };

    return {
      video: [{ container: fallback.container, type: "video", items: [fallback] }],
      audio: [],
      flat: [fallback]
    };
  }

  return { video, audio, flat };
}

function applyServerAvailability(formats, { serverWarning = "", sourceUrl = "", sourceName = "" } = {}) {
  const blockAdaptiveYouTube = !ALLOW_YOUTUBE_ADAPTIVE && (
    isYouTubeLikeSource(sourceUrl) || isYouTubeLikeSource(sourceName)
  );
  const adaptiveReason = blockAdaptiveYouTube
    ? "Higher YouTube qualities like 1080p, 1440p, and 4K are disabled on this server because they need extra YouTube download support. Use a direct quality here, or upgrade the server setup first."
    : serverWarning;

  if (!adaptiveReason) {
    return formats;
  }

  const markItem = (item) => {
    if (item.type === "video" && item.isAdaptive) {
      return {
        ...item,
        disabled: true,
        unavailableReason: adaptiveReason,
        note: `${item.note} • currently unavailable on this server`
      };
    }

    return item;
  };

  const video = formats.video.map((group) => ({
    ...group,
    items: group.items.map(markItem)
  }));
  const audio = formats.audio.map((group) => ({
    ...group,
    items: group.items.map(markItem)
  }));
  const flat = [...video.flatMap((group) => group.items), ...audio.flatMap((group) => group.items)];

  return { video, audio, flat };
}

function normalizeWarningText(stderr = "") {
  const lower = stderr.toLowerCase();

  if (lower.includes("po token") || lower.includes("sabr streaming")) {
    return "Some higher YouTube qualities may need a newer yt-dlp build or a configured YouTube PO token on the server.";
  }

  return "";
}

export async function inspectMedia(sourceUrl) {
  try {
    const cookiesArg = await getCookiesArg();
    const { stdout, stderr } = await execFileAsync(
      YT_DLP_BIN,
      ["--ignore-config", "--geo-bypass", "--verbose", "--no-cache-dir", "--js-runtimes", "node", ...cookiesArg, "--dump-single-json", "--no-playlist", "--skip-download", sourceUrl],
      { maxBuffer: 20 * 1024 * 1024 }
    );

    const info = JSON.parse(stdout);
    const baseFormats = normalizeFormats(info);
    const serverWarning = normalizeWarningText(stderr);
    const formats = applyServerAvailability(baseFormats, {
      serverWarning,
      sourceUrl,
      sourceName: info.extractor_key || info.extractor || info.webpage_url_domain || ""
    });
    const title = sanitizeFilename(info.title || "Untitled media", "Untitled media");

    return {
      sourceUrl,
      title,
      description: info.description ? info.description.slice(0, 180) : null,
      thumbnail: info.thumbnail || info.thumbnails?.at?.(-1)?.url || null,
      sourceName: formatSourceName(info.extractor_key || info.extractor || info.webpage_url_domain || ""),
      durationLabel: formatDurationSeconds(info.duration),
      durationSeconds: info.duration || 0,
      uploader: info.uploader || info.channel || info.creator || null,
      uploadDate: info.upload_date || null,
      formats: formats.flat,
      formatGroups: {
        video: formats.video,
        audio: formats.audio
      },
      serverWarning
    };
  } catch (error) {
    if (error.code === "ENOENT") {
      throw createYtError("yt-dlp is not installed on this server yet. Install yt-dlp and ffmpeg first.", 503);
    }

    const stderr = error.stderr?.trim();
    throw createYtError(stderr || error.message || "This link could not be inspected right now.", 400);
  }
}

function buildDownloadArgs({ sourceUrl, selector, mode, ext, outputTemplate }) {
  const args = ["--ignore-config", "--geo-bypass", "--js-runtimes", "node", "--no-warnings", "--no-playlist"];

  if (mode === "extract-audio") {
    args.push(
      "-f",
      selector || "bestaudio/best",
      "-x",
      "--audio-format",
      normalizeExt(ext, "mp3"),
      "--audio-quality",
      "0",
      "-o",
      outputTemplate,
      sourceUrl
    );

    return args;
  }

  args.push("-f", selector || "best");

  if (mode === "merge") {
    args.push("--merge-output-format", normalizeExt(ext, "mp4"));
  }

  args.push("-o", outputTemplate, sourceUrl);
  return args;
}

function buildDownloadError(stderr = "") {
  const lower = stderr.toLowerCase();

  if (lower.includes("http error 403") || lower.includes("po token") || lower.includes("sabr")) {
    return createYtError(
      "This quality needs a newer yt-dlp build or extra YouTube server support before it can download reliably. Update yt-dlp first, then try again.",
      409
    );
  }

  return createYtError(stderr || "The download could not be prepared.", 500);
}

async function createTempOutputDir() {
  const dir = path.join(TMP_ROOT, createTempId());
  await mkdir(dir, { recursive: true });
  return dir;
}

async function locateCompletedFile(directoryPath) {
  const entries = await readdir(directoryPath, { withFileTypes: true });
  const files = entries
    .filter((entry) => entry.isFile() && !entry.name.endsWith(".part"))
    .map((entry) => path.join(directoryPath, entry.name));

  if (!files.length) {
    throw createYtError("The server could not find the finished media file.", 500);
  }

  return files[0];
}

export async function streamDownloadDirect({ sourceUrl, selector, ext }) {
  const args = ["--ignore-config", "--geo-bypass", "--js-runtimes", "node", "--no-warnings", "--no-playlist", "-f", selector || "best", "-o", "-", sourceUrl];
  const cookiesArg = await getCookiesArg();
  args.unshift(...cookiesArg);

  const child = spawn(YT_DLP_BIN, args, {
    stdio: ["ignore", "pipe", "pipe"]
  });

  const stderrChunks = [];
  child.stderr.on("data", (chunk) => {
    stderrChunks.push(chunk);
  });

  return new ReadableStream({
    start(controller) {
      child.stdout.on("data", (chunk) => {
        controller.enqueue(new Uint8Array(chunk));
      });

      child.stdout.on("end", () => {
        if (child.exitCode !== null && child.exitCode !== 0) {
          const stderr = Buffer.concat(stderrChunks).toString().trim();
          console.error(`yt-dlp stream exited with code ${child.exitCode}: ${stderr}`);
        }
        controller.close();
      });

      child.stdout.on("error", (error) => {
        controller.error(error);
        child.kill();
      });
    },
    cancel() {
      child.kill();
    }
  });
}

export async function prepareDownloadFile({ sourceUrl, selector, mode, ext, downloadId }) {
  const outputDir = await createTempOutputDir();
  const outputTemplate = path.join(outputDir, "%(title)s.%(ext)s");
  const args = buildDownloadArgs({
    sourceUrl,
    selector,
    mode,
    ext,
    outputTemplate
  });

  const cookiesArg = await getCookiesArg();
  args.unshift(...cookiesArg);

  if (downloadId) {
    activeDownloads.set(downloadId, { status: "downloading", progress: 0 });
  }

  const child = spawn(YT_DLP_BIN, args, {
    stdio: ["ignore", "pipe", "pipe"]
  });

  child.stdout.on("data", (chunk) => {
    const text = chunk.toString();
    const match = text.match(/\[download\]\s+(\d+(?:\.\d+)?)%/);
    if (match && downloadId) {
      const progress = parseFloat(match[1]);
      activeDownloads.set(downloadId, { status: "downloading", progress });
    }
  });

  const stderrChunks = [];
  child.stderr.on("data", (chunk) => {
    const text = chunk.toString();
    stderrChunks.push(Buffer.from(chunk));

    if (downloadId && (text.includes("[Merger]") || text.includes("Merging formats") || text.includes("ffmpeg"))) {
      activeDownloads.set(downloadId, { status: "merging", progress: 99 });
    }
  });

  const exitCode = await new Promise((resolve, reject) => {
    child.once("error", (error) => {
      if (downloadId) {
        activeDownloads.set(downloadId, { status: "failed", error: error.message || "Failed" });
      }
      if (error.code === "ENOENT") {
        reject(createYtError("yt-dlp is not installed on this server yet. Install yt-dlp and ffmpeg first.", 503));
        return;
      }

      reject(createYtError(error.message || "The download process could not start.", 500));
    });

    child.once("close", resolve);
  });

  if (exitCode !== 0) {
    if (downloadId) {
      activeDownloads.set(downloadId, { status: "failed", error: "Process exited with non-zero code" });
    }
    const stderr = Buffer.concat(stderrChunks).toString("utf8").trim();
    await rm(outputDir, { recursive: true, force: true }).catch(() => null);
    throw buildDownloadError(stderr);
  }

  const filePath = await locateCompletedFile(outputDir);
  const cleanup = async () => {
    await rm(outputDir, { recursive: true, force: true }).catch(() => null);
  };

  if (downloadId) {
    activeDownloads.set(downloadId, {
      status: "completed",
      progress: 100,
      filePath,
      cleanup
    });

    // Auto-cleanup after 5 minutes if client never fetches it
    setTimeout(async () => {
      const entry = activeDownloads.get(downloadId);
      if (entry && entry.filePath === filePath) {
        try {
          await cleanup();
        } catch (e) {
          console.error("Auto-cleanup failed:", e);
        }
        activeDownloads.delete(downloadId);
      }
    }, 5 * 60 * 1000);
  }

  return {
    filePath,
    cleanup
  };
}

export function getDownloadHeaders({ filename, ext, size }) {
  const safeName = sanitizeFilename(filename, "download");
  const finalExt = normalizeExt(ext, "mp4");

  const headers = {
    "Cache-Control": "no-store",
    "Content-Type": guessMimeType(finalExt),
    "Content-Disposition": `attachment; filename*=UTF-8''${encodeURIComponent(`${safeName}.${finalExt}`)}`
  };

  if (size && size > 0) {
    headers["Content-Length"] = String(size);
  }

  return headers;
}

export function createReadableStreamFromFile(filePath, onFinish) {
  const nodeStream = createReadStream(filePath);

  return new ReadableStream({
    start(controller) {
      nodeStream.on("data", (chunk) => {
        controller.enqueue(new Uint8Array(chunk));
      });

      nodeStream.on("end", async () => {
        controller.close();
        if (onFinish) {
          await onFinish();
        }
      });

      nodeStream.on("error", async (error) => {
        controller.error(error);
        if (onFinish) {
          await onFinish();
        }
      });
    },
    async cancel() {
      nodeStream.destroy();
      if (onFinish) {
        await onFinish();
      }
    }
  });
}
